version: '3.8'

services:

  web:
    build: ./src
    command: gunicorn -w 1 'app:app' -b 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@post_db:5432/blog_db
    depends_on:
      - post_db

  post_db:
    image: postgres:16.2
    expose:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog_db
